### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ginn13** [fluxcd/notification-controller#471]
### Decription of problem
notification-controller v0.27.0 got panic while reconciling Alert, created beforehead.
Manual restart of notification-controller pod has no effect.
A full copy of Alert with another name got reconciled successfully.
Cannot reproduce on notification-controller v0.31.0
### Additional info
Kubernetes v1.24.6
notification-controller v0.27.0
#### notification-controller spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: notification-controller-689d9b485f-fbntx
  generateName: notification-controller-689d9b485f-
  namespace: flux-system
  uid: cf8b1b56-486f-451b-9d3e-24b2ac6957cf
  resourceVersion: '3045007'
  creationTimestamp: '2023-02-03T10:44:53Z'
  labels:
    app: notification-controller
    pod-template-hash: 689d9b485f
  annotations:
    cni.projectcalico.org/containerID: 5b84ecd66f413297d6a9d02369b8af93fb37fffdcd6a58a17d84fea70ba09ac3
    cni.projectcalico.org/podIP: 10.233.82.34/32
    cni.projectcalico.org/podIPs: 10.233.82.34/32
    container.seccomp.security.alpha.kubernetes.io/manager: runtime/default
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: notification-controller-689d9b485f
      uid: 0a5dcea3-b821-48a6-b4ef-b0211ffd06a0
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-02-03T10:44:53Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:prometheus.io/port: {}
            f:prometheus.io/scrape: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0a5dcea3-b821-48a6-b4ef-b0211ffd06a0"}: {}
        f:spec:
          f:containers:
            k:{"name":"manager"}:
              .: {}
              f:args: {}
              f:env:
                .: {}
                k:{"name":"RUNTIME_NAMESPACE"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:livenessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":8080,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
                k:{"containerPort":9090,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
                k:{"containerPort":9292,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
                k:{"containerPort":9440,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
              f:readinessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:securityContext:
                .: {}
                f:allowPrivilegeEscalation: {}
                f:capabilities:
                  .: {}
                  f:drop: {}
                f:readOnlyRootFilesystem: {}
                f:runAsNonRoot: {}
                f:seccompProfile:
                  .: {}
                  f:type: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/tmp"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:nodeSelector: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext:
            .: {}
            f:fsGroup: {}
          f:serviceAccount: {}
          f:serviceAccountName: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"temp"}:
              .: {}
              f:emptyDir: {}
              f:name: {}
    - manager: calico
      operation: Update
      apiVersion: v1
      time: '2023-02-03T10:44:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-02-03T10:44:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.233.82.34"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
  selfLink: /api/v1/namespaces/flux-system/pods/notification-controller-689d9b485f-fbntx
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-03T10:44:53Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-03T10:44:55Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-03T10:44:55Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-03T10:44:53Z'
  hostIP: 10.120.92.70
  podIP: 10.233.82.34
  podIPs:
    - ip: 10.233.82.34
  startTime: '2023-02-03T10:44:53Z'
  containerStatuses:
    - name: manager
      state:
        running:
          startedAt: '2023-02-03T10:44:55Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: ghcr.io/fluxcd/notification-controller:v0.27.0
      imageID: >-
        ghcr.io/fluxcd/notification-controller@sha256:12afde7e3f2a93f2b95f87b391035a38ecbee78d3a47a829f337e28a9a86de4b
      containerID: cri-o://8fb9f63e3ed946398e208c406d762bf0bcae27473f9d5bbc680b6b87b2e2f734
      started: true
  qosClass: Burstable
spec:
  volumes:
    - name: temp
      emptyDir: {}
    - name: kube-api-access-fsw67
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: manager
      image: ghcr.io/fluxcd/notification-controller:v0.27.0
      args:
        - '--watch-all-namespaces=true'
        - '--log-level=info'
        - '--log-encoding=json'
        - '--enable-leader-election'
      ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        - name: http-webhook
          containerPort: 9292
          protocol: TCP
        - name: http-prom
          containerPort: 8080
          protocol: TCP
        - name: healthz
          containerPort: 9440
          protocol: TCP
      env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - name: temp
          mountPath: /tmp
        - name: kube-api-access-fsw67
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /healthz
          port: healthz
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /readyz
          port: healthz
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Always
  terminationGracePeriodSeconds: 10
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: notification-controller
  serviceAccount: notification-controller
  nodeName: ss-k8slb-st01
  securityContext:
    fsGroup: 1337
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
```
#### Alert spec:
```apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  annotations:
    meta.helm.sh/release-name: site-stg
    meta.helm.sh/release-namespace: site-stg
  creationTimestamp: '2023-02-02T11:57:17Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2023-02-02T11:57:18Z'
  finalizers:
    - finalizers.fluxcd.io
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
    - apiVersion: notification.toolkit.fluxcd.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:spec:
          .: {}
          f:eventSeverity: {}
          f:eventSources: {}
          f:providerRef:
            .: {}
            f:name: {}
      manager: helm
      operation: Update
      time: '2023-02-02T11:57:17Z'
    - apiVersion: notification.toolkit.fluxcd.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"finalizers.fluxcd.io": {}
      manager: notification-controller
      operation: Update
      time: '2023-02-02T11:57:17Z'
  name: flux-helmreleases
  namespace: flux-system
  resourceVersion: '2481547'
  uid: 6c3de3d8-69fb-4636-a6e4-74c86f4069a9
  selfLink: >-
    /apis/notification.toolkit.fluxcd.io/v1beta1/namespaces/flux-system/alerts/flux-helmreleases
status:
  observedGeneration: -1
spec:
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: site-stg
    - kind: HelmRelease
      name: '*'
      namespace: monitoring
    - kind: HelmRelease
      name: '*'
      namespace: operators
    - kind: HelmRelease
      name: '*'
      namespace: gitlab
    - kind: HelmRelease
      name: '*'
      namespace: vault-infra
  providerRef:
    name: flux-telegram
```
#### Notification-controller Log:
```E0203 10:46:30.716764       6 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 294 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1884160?, 0x2b08650})
	k8s.io/apimachinery@v0.25.2/pkg/util/runtime/runtime.go:75 +0x99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:110 +0xb9
panic({0x1884160, 0x2b08650})
	runtime/panic.go:884 +0x212
github.com/fluxcd/notification-controller/controllers.(*AlertReconciler).Reconcile.func1()
	github.com/fluxcd/notification-controller/controllers/alert_controller.go:140 +0x225
github.com/fluxcd/notification-controller/controllers.(*AlertReconciler).Reconcile(0xc000720ec0, {0x1de32b8, 0xc0019d0480}, {{{0xc0007057f0?, 0x10?}, {0xc000671320?, 0x40dc87?}}})
	github.com/fluxcd/notification-controller/controllers/alert_controller.go:167 +0x56b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1de3210?, {0x1de32b8?, 0xc0019d0480?}, {{{0xc0007057f0?, 0x1a48400?}, {0xc000671320?, 0x4045d4?}}})
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002ed040, {0x1de3210, 0xc000720d40}, {0x1928e80?, 0xc000432a60?})
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002ed040, {0x1de3210, 0xc000720d40})
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:230 +0x333
{"level":"error","ts":"2023-02-03T10:46:30.720Z","msg":"Reconciler error","controller":"alert","controllerGroup":"notification.toolkit.fluxcd.io","controllerKind":"Alert","Alert":{"name":"flux-helmreleases","namespace":"flux-system"},"namespace":"flux-system","name":"flux-helmreleases","reconcileID":"44555714-d1af-41ee-8966-3066769081fe","error":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
```

**Comment by stefanprodan** [comment]
@ginn13 we don't do backports, if the latest version works Ok then it's nothing for us to do.

**Comment by ginn13** [comment]
Ok, then I close.
